<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-CAKSD5A" failures="0" tests="5" name="com.TestNGDemos.D13CreateLoginFile" time="0.010" errors="1" timestamp="2025-02-18T20:01:57 IST" skipped="4">
  <testcase classname="com.TestNGDemos.D13CreateLoginFile" name="beforeTest" time="0.010">
    <error message="ExcelFiles\LoginData.xlsx (The system cannot find the path specified)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: ExcelFiles\LoginData.xlsx (The system cannot find the path specified)
at java.base/java.io.FileOutputStream.open0(Native Method)
at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:185)
at com.TestNGDemos.D13CreateLoginFile.beforeTest(D13CreateLoginFile.java:55)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- beforeTest -->
  <system-out/>
  <testcase classname="com.TestNGDemos.D13CreateLoginFile" name="createLoginFile" time="0.000">
    <skipped/>
  </testcase> <!-- createLoginFile -->
  <system-out/>
  <testcase classname="com.TestNGDemos.D13CreateLoginFile" name="createLoginFile" time="0.000">
    <skipped/>
  </testcase> <!-- createLoginFile -->
  <system-out/>
  <testcase classname="com.TestNGDemos.D13CreateLoginFile" name="createLoginFile" time="0.000">
    <skipped/>
  </testcase> <!-- createLoginFile -->
  <system-out/>
  <testcase classname="com.TestNGDemos.D13CreateLoginFile" name="createLoginFile" time="0.000">
    <skipped/>
  </testcase> <!-- createLoginFile -->
  <system-out/>
</testsuite> <!-- com.TestNGDemos.D13CreateLoginFile -->
